sylius_admin_attribute_group:
    resource: |
        alias: bitbag_sylius_product_attribute_group_plugin.group
        except: ['show']
        section: admin
        templates: "@SyliusAdmin/Crud"
        grid: bitbag_sylius_product_attribute_group
    type: sylius.resource
    prefix: /product-attribute-groups-plugin
