sylius_grid:
  grids:
    bitbag_sylius_product_attribute_group:
      driver:
        options:
          class: BitBag\SyliusProductAttributeGroupsPlugin\Entity\Group
      fields:
        name:
          type: string
          label: bitbag_sylius_product_attribute_group_plugin.ui.name
        attributes:
          type: twig
          label: bitbag_sylius_product_attribute_group_plugin.ui.attributes
          options:
            template: "@BitBagSyliusProductAttributeGroupsPlugin/Grid/Field/attributes.html.twig"
      actions:
        main:
          create:
            type: create
        item:
          update:
            type: update
          delete:
            type: delete
