bitbag_sylius_product_attribute_groups_plugin:
  resource: |
    alias: bitbag_sylius_product_attribute_group_plugin.group
    path: /product-attribute-groups-plugin
    except: ['show']
    section: admin
    templates: "@SyliusAdmin/Crud"
    grid: bitbag_sylius_product_attribute_group
  type: sylius.resource
