BitBag\SyliusProductAttributeGroupsPlugin\Entity\Attribute:
    type: entity
    table: bitbag_product_attribute
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToOne:
        group:
            targetEntity: BitBag\SyliusProductAttributeGroupsPlugin\Entity\Group
            joinColumn:
                name: group_id
                referencedColumnName: id
    oneToOne:
        syliusAttribute:
            targetEntity: Sylius\Component\Attribute\Model\AttributeInterface
            joinColumn:
                name: sylius_attribute_id
                referencedColumnName: id
